<?php


class testBox extends Box {
    /**
     * @var float
     */
    public $lineHeight = 1.25;

    /**
     * @var int
     */
    public $fontSize = 12;

    public function calculateBox($text) {
        return parent::calculateBox($text); // TODO: Change the autogenerated stub
    }

    public function wrapTextWithOverflow($text) {
        return parent::wrapTextWithOverflow($text); // TODO: Change the autogenerated stub
    }
}